### PR TITLE
Implement proposal issue#19

### PR DESCRIPTION
**Pull request by photowey**
fixed https://github.com/alibaba/IOC-Golang/issues/19

### CODE REVIEW

**Comment by photowey** [comment]
```
I read your commit carefully, and the optimization is also very reasonable. 
The only thing I don't agree with is that the config parameter separator "." is changed to "#".
```



```
We can think of other ways to circumvent this problem, such as:

1. Full-text search in the parameter chain to see if there is a registered SDID (full-name or alias). 
If it exists, treat it as a whole.
```

`e.g.:`

```
LoadConfigByPrefix("autowire.normal.github.com/alibaba/ioc-golang/extension/normal/redis.Impl.param", redisConfig)

-> github.com/alibaba/ioc-golang/extension/normal/redis.Impl -> SDID
-> github.com/alibaba/ioc-golang/extension/normal/redis.Impl == REDIS
-> autowire.normal.REDIS.param
```



```
2. A special mark is added to identify the modified part as a whole and indivisible.
```
`e.g.:`
```yml
autowire:
  normal:
    <github.com/alibaba/ioc-golang/extension/normal/redis.Impl>: # <xxx>
      env-redis:
        param:
          _ioc_golang_config_source: env
          address: REDIS_ADDRESS
          db: 1
      normal-redis:
        param:
          _ioc_golang_config_source: normal
          address: localhost:26379
          db: 2
      param:
        address: localhost:6379
        db: 0
```



```go
LoadConfigByPrefix("autowire.normal.<github.com/alibaba/ioc-golang/extension/normal/redis.Impl>.param", redisConfig)
```

**Comment by LaurenceLiZhixin** [comment]
@photowey 
我按照你说的改下，我认为后者更明确些。
在LoadConfigByPrefix的API处使用"<>"来标注路径，避免 '.' 字符冲突，"<>" 的作用仅用于此，例如：
```go
LoadConfigByPrefix("autowire.normal.<github.com/alibaba/ioc-golang/extension/normal/redis.Impl>.param", redisConfig)
```
在yaml文件配置中，我认为不需要<>标注，因为不会在解析yaml的时候产生冲突。

**Comment by photowey** [comment]
`Config file without any modification`

```yml
autowire:
  normal:
    github.com/alibaba/ioc-golang/extension/normal/redis.Impl:
      env-redis:
        param:
          _ioc_golang_config_source: env
          address: REDIS_ADDRESS
          db: 1
      normal-redis:
        param:
          _ioc_golang_config_source: normal
          address: localhost:26379
          db: 2
      param:
        address: localhost:6379
        db: 0
```



```go
// <github.com/alibaba/ioc-golang/extension/normal/redis.Impl>
LoadConfigByPrefix("autowire.normal.<github.com/alibaba/ioc-golang/extension/normal/redis.Impl>.param", redisConfig)
```

`Use regex extract`

```go
func RegexpExtract(regex, src, alias string) string {
	var result []byte
	pattern := regexp.MustCompile(regex)
	for _, sub := range pattern.FindAllStringSubmatchIndex(src, -1) {
		result = pattern.ExpandString(result, alias, src, sub)
	}

	return string(result)
}
```



```go
func TestRegexpExtract(t *testing.T) {
	type args struct {
		regex string
		src   string
		temp  string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "Test RegexpExtract-1",
			args: args{
				regex: `(.*<)(?P<sdid>[\S]+)(>.*)`,
				src:   "autowire.normal.<github.com/alibaba/ioc-golang/extension/normal/redis.Impl>.normal-redis.param",
				temp:  "$sdid",
			},
			want: "github.com/alibaba/ioc-golang/extension/normal/redis.Impl",
		},
		{
			name: "Test RegexpExtract-2",
			args: args{
				regex: `(.*<)(?P<sdid>[\S]+)(>.*)`,
				src:   "autowire.normal.<github.com/alibaba/ioc-golang/extension/normal/redis.Impl.normal-redis.param",
				temp:  "$sdid",
			},
			want: "",
		},
		{
			name: "Test RegexpExtract-3",
			args: args{
				regex: `(.*<)(?P<sdid>[\S]+)(>.*)`,
				src:   "autowire.normal.github.com/alibaba/ioc-golang/extension/normal/redis.Impl>.normal-redis.param",
				temp:  "$sdid",
			},
			want: "",
		},
		{
			name: "Test RegexpExtract-4",
			args: args{
				regex: `(.*<)(?P<sdid>[\S]+)(>.*)`,
				src:   "autowire.normal.github.com/alibaba/ioc-golang/extension/normal/redis.Impl.normal-redis.param",
				temp:  "$sdid",
			},
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := RegexpExtract(tt.args.regex, tt.args.src, tt.args.temp); got != tt.want {
				t.Errorf("RegexpExtract() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

**Comment by photowey** [comment]
I still prefer to use a regular expression to first determine if a qualifying SDID is included in the parameter chain.
For example, ineligible SDID: "autowire.normal.<xxx/redis.Impl.normal-redis.param".
Alternatively, you also need to validate whether the "<" and ">" pair of identifiers are paired.
However, this is just my personal opinion and may be complicated by me.

**Comment by LaurenceLiZhixin** [comment]
@photowey 
这块独立题一个issue，单独提pr把。这个pr已经够大了，除了这个别的还有问题么？

**Comment by photowey** [comment]
All is well!
see: [helloioc](https://github.com/photowey/helloioc)

**Pull request merged**
